
spring:
  application:
    name: PTO_ACKYE_RZHD
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://62.76.142.52:5433/ackyedb
    username: ackye
    password: ackyepass
    driver-class-name: org.postgresql.Driver

telegram:
  bot:
    name: ACKYE_bot
    token: 8409445913:AAG5joeDB5aob6_fgAT4u7b3oUUd4KunwJQ
    owner: 199867696

#cron:
#  scheduler: 0 * * * * *
logging:
  level:
    ru.jngvarr: DEBUG
#    org.springframework: DEBUG
    org.springframework.cloud.config: DEBUG
server:
  port: 8081

